### ISSUE TITLE
ldg only available on sm_32+

### ISSUE THREAD

**Issue by MoonCoral** [JuliaGPU/CUDAnative.jl#249]
The following error happens many times when running `test CUDAnative`
```
TypeError: in irgen, in typeassert, expected RegexMatch, got Nothing
  Stacktrace:
[1] irgen(::CUDAnative.CompilerContext) at /home/othill/.julia/packages/CUDAnative/EsWDI/src/compiler/irgen.jl:168
...
```
The full output can be found here https://gist.github.com/MoonCoral/b3d13a15dfd6e9af00408c8daba7171d

**Comment by maleadt** [comment]
Julia `versioninfo()`?

**Comment by MoonCoral** [comment]
The above was from a 10 day old build from julia master.

I recompiled julia since but that type of error still crops up but less often and there are other errors which seem similar to #165.
https://gist.github.com/MoonCoral/b04cb4d169d3aa9f204a1f10b4cc54fd

```julia
julia> versioninfo()
Julia Version 1.1.0-DEV.236
Commit 7142712 (2018-09-11 14:40 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, haswell)
```

ext.jl in case it matters
```julia
# autogenerated file, do not edit
const ptx_support = VersionNumber[v"3.2.0", v"4.0.0", v"4.1.0", v"4.2.0", v"4.3.0", v"5.0.0", v"6.0.0"]
const cuobjdump = "/usr/local/cuda-9.2/bin/cuobjdump"
const configured = true
const libdevice = "/usr/local/cuda-9.2/nvvm/libdevice/libdevice.10.bc"
const target_support = VersionNumber[v"3.0.0", v"3.2.0", v"3.5.0", v"3.7.0", v"5.0.0", v"5.2.0", v"5.3.0", v"6.0.0", v"6.1.0", v"6.2.0", v"7.0.0"]
const cuda_driver_version = v"9.2.0"
const ptxas = "/usr/local/cuda-9.2/bin/ptxas"
```

P.S. LLVM passes all it's tests as does julia itself (make test).

**Comment by maleadt** [comment]
Ah, well I haven't been working on 1.1-dev aka master lately. Any reason you're working with a bleeding-edge Julia? I don't think I have the time to actively keep CUDAnative working with master at this point.

**Comment by maleadt** [comment]
> errors which seem similar to #165.

That issue describes a build failure, so I'm not sure what you are referring to. If you mean the `no method matching start(::Base.DevNullStream)` errors near the bottom, that is evident of a pre-0.7 version of Julia (which I expected you to be using given the issue you described above).

**Comment by MoonCoral** [comment]
Using the official Binaries the TypeError is absent. So maybe it is caused by my julia build.

However the
```julia
Error During Test at /home/othill/.julia/packages/CUDAnative/EsWDI/test/device/pointer.jl:12
  Got exception outside of a @test
  CUDA error: a PTX JIT compilation failed (code #218, ERROR_INVALID_PTX)
  ptxas application ptx input, line 24; error   : Instruction 'ld.nc' requires .target sm_32 or higher
  ptxas fatal   : Ptx assembly aborted due to errors
```
errors remain even with the official binaries. Those are the ones I was referring to as seeming similar to the older issue.

**Comment by maleadt** [comment]
Ah, that one is interesting. You seem to have a pretty old GPU, where `ldg` is not available. This is tough to fix right now, since it relies on contextual dispatch in order to fallback/error when you're using the functionality on an older GPU. I'll add a guard to the tests, though.

**Comment by MoonCoral** [comment]
I see. Thank you.

**Comment by maleadt** [comment]
re https://github.com/JuliaGPU/CUDAnative.jl/issues/249#issuecomment-420555632, compatibility with Julia `master` fixed in https://github.com/JuliaGPU/CUDAnative.jl/commit/555da5e9007f226e8e15e8705504ccb7b7e85d56 (for now)
